[font]
size = 20 

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Ubuntu",
    "--cd",
    "~"
]
